### ISSUE TITLE
关于后台自动下载更新包问题

### ISSUE THREAD

**Issue by mpamxl** [Bush2021/chrome_plus#10]
现版如果在旧版Chrome使用，会自动在C:\Program Files\Google、C:\Users\Administrator\AppData\Local\Google下创建Update自动下载新版并自动安装，目前我尝试创建占位文件可以阻止，但可以有办法从Chrome++中想办法彻底阻止创建这两个路径的文件夹吗？

**Comment by Bush2021** [comment]
你是怎么使用 Chrome++ 的？一般推荐的操作是下载[离线安装包](https://chrome.noki.eu.org/)，手动解压使用；

而离线安装包是不带更新程序的，所以至少我测试不会创建你说的那些内容，但有人反馈说会有更新气泡，我倒是没能复现；

我认为不应该由 Chrome++ 决定是否阻止 Chrome 在其它路径创建文件夹，创建只读占位文件更合理一点。

**Comment by mpamxl** [comment]
是离线安装包，之前我也一直正常使用，但后面无意发现旧版会自动在C盘的那两个路径创建文件夹并且后台自动下载新版到Update文件夹内安装到C盘，如果你本身用的版本比较新不会出现这个问题，但旧版会，比如80多版本甚至100左右版本或者更老的版本，如果需要我可以全新使用录屏给你看下问题情况，占位文件创建后确实可以解决，但这个占位文件得在C盘，或者有没办法捕获这两个路径的代码拦截到便携版的Data里，这样Data里放占位文件就不用手动去C盘放了

**Comment by mpamxl** [comment]
至于更新气泡和旧版的设置按钮提示版本太旧的问题，可以通过参数--disable-background-networking解决

**Comment by Bush2021** [comment]
> 是离线安装包，之前我也一直正常使用，但后面无意发现旧版会自动在C盘的那两个路径创建文件夹并且后台自动下载新版到Update文件夹内安装到C盘，如果你本身用的版本比较新不会出现这个问题，但旧版会，比如80多版本甚至100左右版本或者更老的版本，如果需要我可以全新使用录屏给你看下问题情况，占位文件创建后确实可以解决，但这个占位文件得在C盘，或者有没办法捕获这两个路径的代码拦截到便携版的Data里，这样Data里放占位文件就不用手动去C盘放了

先排查一下启动项和服务吧，我之前有同时装 87 版本的 Chrome，也没遇到过这个问题；即使确实存在，你放一个占位文件在 C 盘又有什么影响吗，我不认为这种功能需要在 Chrome++ 里实现；

或者，你可以尝试第三方编译的 Chromium，彻底移除了更新，比如 [https://github.com/Hibbiki/chromium-win64/releases](https://github.com/Hibbiki/chromium-win64/releases)；

Chrome++ 是为最新版本设计的，所以不太可能会去适配旧版本的功能；

> 至于更新气泡和旧版的设置按钮提示版本太旧的问题，可以通过参数--disable-background-networking解决

这个参数会导致扩展无法更新等问题，不建议使用。

**Comment by yleafcc** [comment]
> > 是离线安装包，之前我也一直正常使用，但后面无意发现旧版会自动在C盘的那两个路径创建文件夹并且后台自动下载新版到Update文件夹内安装到C盘，如果你本身用的版本比较新不会出现这个问题，但旧版会，比如80多版本甚至100左右版本或者更老的版本，如果需要我可以全新使用录屏给你看下问题情况，占位文件创建后确实可以解决，但这个占位文件得在C盘，或者有没办法捕获这两个路径的代码拦截到便携版的Data里，这样Data里放占位文件就不用手动去C盘放了
> 
> 先排查一下启动项和服务吧，我之前有同时装 87 版本的 Chrome，也没遇到过这个问题；即使确实存在，你放一个占位文件在 C 盘又有什么影响吗，我不认为这种功能需要在 Chrome++ 里实现；
> 
> 或者，你可以尝试第三方编译的 Chromium，彻底移除了更新，比如 https://github.com/Hibbiki/chromium-win64/releases；
> 
> Chrome++ 是为最新版本设计的，所以不太可能会去适配旧版本的功能；
> 
> > 至于更新气泡和旧版的设置按钮提示版本太旧的问题，可以通过参数--disable-background-networking解决
> 
> 这个参数会导致扩展无法更新等问题，不建议使用。

那如何避免提示Chrome更新相关的问题呢？更新太频繁了。

**Comment by Bush2021** [comment]
> 那如何避免提示Chrome更新相关的问题呢？更新太频繁了。

"wontfix", "not planned"，请不要继续在已经关闭的 issue 里回复。
