### ISSUE TITLE
老板键的问题，可否优化一下？

### ISSUE THREAD

**Issue by Azreulo** [Bush2021/chrome_plus#100]
情况是这样的，平时同时用CentBrowser和Chrome，在插件里设置老板键Alt+～， CentBrowser设置老板键Ctrl+～。

按Alt+～，"CentBrowser和Chrome都会被隐藏（CentBrowser的进程名也是Chrome.exe）"，但是按Ctrl+～，"只有CentBrowser被正确隐藏，Chrome不会被隐藏。能否增加个判断，正确隐藏？"

另，兄弟是CCF的Bush吗？

**Comment by Bush2021** [comment]
https://github.com/Bush2021/chrome_plus/releases/tag/1.10.0
