### ISSUE TITLE
Two problems

### ISSUE THREAD

**Issue by Jasantes** [Bush2021/chrome_plus#107]
Hello, this piece of code is a little jewel...
I used command line flags to relocate my profile, but this is much better!!!
However, I found two problems:
1- **chrome://flags > Restart** or **chrome://restart** do not restart, just close. 
2- Password manager does no record added or imported passwords. It is empty on every startup. I have #disable-encryption > Disabled

**Comment by Bush2021** [comment]
1. Unable to reproduce.

2. Try turning off https://github.com/Bush2021/chrome_plus/blob/f5848328bd8729fce1aae71b0f5e17f588b6c1f8/src/chrome%2B%2B.ini#L61 Note that you need to clear your cache to make this switch take effect.

**Comment by Jasantes** [comment]
1- Still won't restart.
2- show_password was already set to 1, but Password manager is not working.
Maybe this can help: 
![Capture](https://github.com/user-attachments/assets/34a5532a-6cac-45e1-b166-11d0f787bdd4)
