### ISSUE TITLE
Launch browser with CommandLine switches from chrome++.ini doesn't work

### ISSUE THREAD

**Issue by darterias** [Bush2021/chrome_plus#11]
If you enter CommandLine switches in chrome++.ini, then by going to chrome://version/ you will see that quotes are added to them.
For example --disk-cache-size=1 would look like --disk-cache-size="1

![https://i.ibb.co/qyWQFHj/g.gif](https://i.ibb.co/qyWQFHj/g.gif)

**Comment by Bush2021** [comment]
Thank you for your feedback. Version 1.5.8 has a special treatment for "=", which should solve this problem.

I'm sorry that this function is still very rough and needs continuous improvement. Thanks again.

**Comment by darterias** [comment]
Thanks for fixing the bug. In the new version the switches work. 👍
