### ISSUE TITLE
(Improvement)  move  "Service Worker" to "Cache" folder and preference "Clear Cache on exit"

### ISSUE THREAD

**Issue by cra3yk** [Bush2021/chrome_plus#115]
Hi

Big thank You for chrome plus (I'm using mostly to mitigate preference encryption by chrome/chromium).

The separate Cache folder is great idea, but there is another "big boy" folder, that is often full of garbage - Service Worker (which is in profile -> Default -> Service Worker). It is keep growing over time and if You delete it, then the next visit to web site (that using service workers) will recreate it with its content - no big loss.

But the current version of "chrome plus" has a lack of "clear cache on exit" switch/preference (1 - clear, 0 - leave).
It will be great to have one 😄 

Please 😃

**Comment by Bush2021** [comment]
The Cache folder is created by Chrome as part of the browser’s native functionality. Chrome++ only adds command line switches to Chrome without altering its content. Hence, I disagree with moving Service Worker into the Cache folder.

Given the complexity of the user data folder structure and the differing needs of each user, I do not believe it is appropriate for me to specify which "junk" files should be cleared. However, I am open to adding a feature that runs a specific program or script upon Chrome's startup or termination. What do you think?

**Comment by cra3yk** [comment]
>  I am open to adding a feature that runs a specific program or script upon Chrome's startup or termination. What do you think?

Great idea - with this I could run .bat script (or autokey's exe) to clean Cache and Service Worker folder (on exit)

**Comment by Bush2021** [comment]
try https://github.com/Bush2021/chrome_plus/actions/runs/11639738170

**Comment by cra3yk** [comment]
I've tried - it doesn't handle spaces in the path (the chrome.exe is in the path, that contains space)
![obraz](https://github.com/user-attachments/assets/364c701f-3081-4f62-a572-b8c5d96489ea)

**Comment by Bush2021** [comment]
Try adding a semicolon at the end, for example: `launch_on_exit=\"%app%\_clean.cmd\";`

**Comment by cra3yk** [comment]
With semicolon working well.
I want to pass cache and profile  path to my script using this:

`launch_on_exit="%app%\_clean.cmd" "%cache_dir%" "%data_dir%;`

But it seems to that both variables are empty (i can only pass path by name itself)
![obraz](https://github.com/user-attachments/assets/5a4493f8-e2a3-4b35-ad6d-d23d4daccf77)

**Comment by Bush2021** [comment]
> With semicolon working well. I want to pass cache and profile path to my script using this:

In fact, there are still some issues with path handling, and I will make some changes later.

> I want to pass cache and profile path to my script using this:
> `launch_on_exit="%app%\_clean.cmd" "%cache_dir%" "%data_dir%;`
> But it seems to that both variables are empty (i can only pass path by name itself)

This is expected behavior, currently only the Windows standard environment variables and `%app%` are supported.

**Comment by cra3yk** [comment]
Ok. I just made _clean.cmd in this way and my live became simpler ;-)
```
@echo off
rd /s /q "%~dp0..\data\Default\Cache"
rd /s /q "%~dp0..\data\Default\DawnGraphiteCache"
rd /s /q "%~dp0..\data\Default\DawnWebGPUCache"
rd /s /q "%~dp0..\data\Default\GPUCache"
rd /s /q "%~dp0..\data\Default\optimization_guide_hint_cache_store"
rd /s /q "%~dp0..\data\Default\Service Worker"

rd /s /q "%TEMP%\chrome_url_fetcher_*"
del /f "%TEMP%\mat-debug-*"

rd /s /q "%~dp0..\cache"
mkdir "%~dp0..\cache"
exit
```
