### ISSUE TITLE
[Bug] Web Apps not presenting themselves with an individual taskbar icon

### ISSUE THREAD

**Issue by achtchaern** [Bush2021/chrome_plus#122]
### Verify steps

- [X] I have carefully read the [INI configuration file](https://github.com/Bush2021/chrome_plus/blob/main/src/chrome%2B%2B.ini) and understand the function of each configuration item.
- [X] I have not searched for the problem I want to raise in the [Issue Tracker](https://github.com/Bush2021/chrome_plus/issues).
- [X] I have provided the simplest configuration that can be used to reproduce the error I reported.
- [X] I make sure to describe the problem in English.

### Version Information

Chrome++ 1.11.0 and Ungoogled Chromium 125.0.6422.142, (version-irrelevant - same issue with the newest Ungoogled Chromium 130)

### Configuration File

```yaml
[general]
data_dir=none
cache_dir=none
command_line=--disable-crashpad --disable-features=GlobalMediaControls,TabSearchChevronIcon,DownloadBubble,CustomizeChromeSidePanel,Windows10CustomTitlebar
launch_on_startup=
kill_launch_on_exit=0
launch_on_exit=
boss_key=
translate_key=
show_password=0
win32k=0
[tabs]
double_click_close=0
right_click_close=0
keep_last_tab=0
wheel_tab=1
wheel_tab_when_press_rbutton=0
open_url_new_tab=0
open_bookmark_new_tab=0
new_tab_disable=0
new_tab_disable_name="about:blank","新建标签"
```

### Description

Without Chrome++, websites installed as apps show up in the taskbar with an actual icon of the respective web app.
![image](https://github.com/user-attachments/assets/3cc36950-62a8-41ed-a297-0e5a7eb57d94)
With Chrome++ loaded, this feature vanishes and the regular chrome icon is being shown (and it's being grouped together with a regular Chrome window)
![image](https://github.com/user-attachments/assets/4f68399c-6052-4f32-b37a-4632ccaa15c6)

**Comment by Bush2021** [comment]
> - [X] I have not searched for the problem I want to raise in the [Issue Tracker](https://github.com/Bush2021/chrome_plus/issues).

This is not ideal.

> [Bug] Web Apps not presenting themselves with an individual taskbar icon

This should be caused by the original author's modification, and it might not be a bug but intentional. See: https://github.com/Bush2021/chrome_plus/blob/106a60e46a47808bfbb619d0a4fe034d7f984883/src/appid.h#L10

I am not familiar with or using Web Apps, so I cannot work on it.

**Comment by achtchaern** [comment]
> This is not ideal.

It's a bit of a trap if one of the four questions is negated. But I think you know that :)

Anyway, thank you for your answer!
