### ISSUE TITLE
[Feature] 请问，chrome++.ini还要不要放入？Chrome++ v1.11.0的包里已经没有chrome++.ini，放入和不放入有什么差吗？

### ISSUE THREAD

**Issue by dodolook8** [Bush2021/chrome_plus#125]
### Verification Steps

- [X] I have carefully read the [INI configuration file](https://github.com/Bush2021/chrome_plus/blob/main/src/chrome%2B%2B.ini) and understand the function of each configuration item.
- [X] I have not searched for the feature request I want to propose in the [Issue Tracker](https://github.com/Bush2021/chrome_plus/issues) and did not find it.
- [X] I am willing to create a pull request to implement the feature I proposed, otherwise I understand that the issue is likely to be closed.
- [X] I make sure to describe the feature in English.

### Description

请问，chrome++.ini还要不要放入？Chrome++ v1.11.0的包里已经没有chrome++.ini，放入和不放入有什么差吗？

看到zd423打包的绿色版里用的Chrome++ v1.11.0，还有chrome++.ini，想问清楚还有没有必要。

是不是不放就是默认设置，且无法修改，如果自己要修改ini就得继续放进去？谢谢。

**Comment by Bush2021** [comment]
> 是不是不放就是默认设置，且无法修改，如果自己要修改ini就得继续放进去？谢谢。

是的。这次未包含是因为自动打包发版的脚本漏了，下次会包含的。https://github.com/Bush2021/chrome_plus/commit/106a60e46a47808bfbb619d0a4fe034d7f984883

**Comment by dodolook8** [comment]
……   我当不再需要了呢。
