### ISSUE TITLE
[Bug] Not Support WebStorm Debug Feature

### ISSUE THREAD

**Issue by leisurelyclouds** [Bush2021/chrome_plus#127]
### Verify steps

- [X] I have carefully read the [INI configuration file](https://github.com/Bush2021/chrome_plus/blob/main/src/chrome%2B%2B.ini) and understand the function of each configuration item.
- [X] I have not searched for the problem I want to raise in the [Issue Tracker](https://github.com/Bush2021/chrome_plus/issues).
- [X] I have provided the simplest configuration that can be used to reproduce the error I reported.
- [X] I make sure to describe the problem in English.

### Version Information

![image](https://github.com/user-attachments/assets/113e9b57-cc99-4fe5-ac4b-7e26291ff7fe)
![image](https://github.com/user-attachments/assets/7d36285f-1d59-419f-88f9-49311eafc85d)

### Configuration File

```yaml
; This file is the configuration file of Chrome++ (version.dll) in INI format
; Line begins with (;) is a comment statement that has no effect for configuration
; For function switch, you need to manually change it: 0 is off, 1 is on
; If the corresponding option is left blank or does not exist, the default configuration is used
; If this file is deleted, the default configuration will be used, which is the configuration initially presented by this file

; 本文件是 Chrome++ (version.dll) 的配置文件，采用 INI 格式
; 分号（;）开始的行是注释语句，不会产生实际作用
; 如果设置是开关，需要手动修改：0关闭，1开启
; 如果对应选项留空或不存在，表示使用默认配置
; 如果删除本文件，将会使用默认配置，也就是本文件初始呈现的配置


; %app% indicates the directory where chrome.exe resides
; Leave blank to use the default Settings

; %app% 表示 chrome.exe 所在目录
; 留空代表使用默认配置
[General]
DataDir=%app%\..\Data
CacheDir=%app%\..\Cache


; Appends Chromium startup parameters
; You can imitate the form below to write, pay attention to the space, do not wrap
; CommandLine=--no-first-run --disable-logging --no-report-upload

; 追加 Chromium 启动参数
; 可以模仿下面的形式来写，注意空格，不要换行
; CommandLine=--no-first-run --disable-logging --no-report-upload
CommandLine=--disable-features=PrintCompositorLPAC --no-first-run --disable-fre --no-default-browser-check


; Customize a shortcut key that can hide all Chrome windows and restore them when pressed again
; Available keys are: Ctrl, Alt, Shift, Win, F1-F12, 0-9, A-Z,
; Left, Right, Up, Down, ←, →, ↑, ↓, Esc, Tab, Backspace,
; Enter, Space, PrtSc, Scroll, Pause, Insert, Delete,
; End, Home, PageUp, PageDown
; Fill in the format example: Ctrl+Alt+B

; 自定义一个快捷键，按下后可以隐藏所有 Chrome 窗口，再次按下恢复
; 可以使用的键位有：Ctrl、Alt、Shift、Win、F1-F12、0-9、A-Z、
; Left、Right、Up、Down、←、→、↑、↓、Esc、Tab、Backspace、
; Enter、Space、PrtSc、Scroll、Pause、Insert、Delete、
; End、Home、PageUp、PageDown
; 填写格式示例：Ctrl+Alt+B
Bosskey=


; Customize a shortcut key that translates the current page

; 自定义网页翻译的快捷键
TranslateKey=

; double_click_close           -- Double left click to close the tab
; right_click_close            -- Right click to close the tab (pop up the original menu when the Shift key is pressed)
; keep_last_tab                -- Keep the last tab from closing the window (except for manually clicking the close button)
; wheel_tab                    -- Use the mouse wheel to switch tab when the mouse is on the tab bar
; wheel_tab_when_press_rbutton -- Use the mouse wheel to switch tab when the right mouse button is pressed anywhere (if you use mouse gesture software, it will not take effect)
; open_url_new_tab             -- New foreground tab opens the contents entered in address bar (1 for foreground, 2 for background)
; open_bookmark_new_tab        -- New foreground tab opens the bookmark (1 for foreground, 2 for background)
; new_tab_disable              -- If the current tab is a new tab, disable the above two options
; new_tab_disable_name         -- When new_tab_disable is 1, define the tab names that need to be opened new_tab_disable here
;                              -- The names are wrapped in quotes ("") and separated by commas (,) for multiple tabs. These names exist as complements to the built-in list

; double_click_close           -- 双击左键关闭标签页
; right_click_close            -- 右键关闭标签页（按 Shift 键时弹出原有菜单）
; keep_last_tab                -- 保留最后一个标签页不关闭窗口（手动点击关闭按钮除外）
; wheel_tab                    -- 鼠标在标签栏时使用鼠标滚轮切换标签页
; wheel_tab_when_press_rbutton -- 在任何位置按住右键时使用鼠标滚轮切换标签页（若使用了鼠标手势软件则不生效）
; open_url_new_tab             -- 新建前台标签页打开地址栏输入的内容（1为前台，2为后台）
; open_bookmark_new_tab        -- 新建前台标签页打开书签（1为前台，2为后台）
; new_tab_disable              -- 如果当前标签页是新标签页，则禁用上面两个选项
; new_tab_disable_name         -- 当 new_tab_disable 为 1 时，在这里额外定义需要开启 new_tab_disable 的标签页名称
;                              -- 名称使用引号 ("") 包裹，多个标签页用逗号 (,) 分隔。这些名称作为内置列表的补集存在
[tabs]
double_click_close=0
right_click_close=0
keep_last_tab=0
wheel_tab=0
wheel_tab_when_press_rbutton=0
open_url_new_tab=0
open_bookmark_new_tab=0
new_tab_disable=0
new_tab_disable_name="about:blank","新建标签"
```

### Description

When the page is already open, WebStorm's debugging feature is not supported and it only opens an about:blank tab. However, if Chrome is closed, debugging can work normally when restarted.

When debugging in WebStorm, it adds the following parameters: --remote-debugging-port --user-data-dir --no-first-run --disable-fre --no-default-browser-check about:blank

It's suspected that the issue might be related to the --remote-debugging-port and --user-data-dir  parameters.

Under normal circumstances, a new profile Chrome page will be launched.

---
已经打开页面的情况下，不支持WebStorm的Debug调试功能，只会打开一个about:blank标签页。如果关闭chrome，再调试可以正常工作
WebStorm调试时会增加--remote-debugging-port --user-data-dir --no-first-run --disable-fre --no-default-browser-check 相关参数
怀疑和--remote-debugging-port --user-data-dir 参数有关
正常情况下会启动一个新profile的chrome页面

**Comment by Bush2021** [comment]
Try setting `data_dir=none`.

**Comment by leisurelyclouds** [comment]
By setting the following configuration, it works correctly:

```ini
[General]
DataDir=none
```
However, how can I specify the DataDir for regular use in order to store data in a specific folder for easier data synchronization? Is it by creating a shortcut and using the corresponding --user-data-dir parameter in the shortcut?

---

通过设置如下配置，正常工作
```ini
[General]
DataDir=none
```

但是平常使用如何指定DataDir?  以便将数据存放指定文件夹方便同步数据？
是建立快捷方式,快捷方式中使用对应`--user-data-dir`参数？

**Comment by YorkWaugh** [comment]
> By setting the following configuration, it works correctly:
> 
> ```ini
> [General]
> DataDir=none
> ```
> 
> However, how can I specify the DataDir for regular use in order to store data in a specific folder for easier data synchronization? Is it by creating a shortcut and using the corresponding --user-data-dir parameter in the shortcut?
> 
> 通过设置如下配置，正常工作
> 
> ```ini
> [General]
> DataDir=none
> ```
> 
> 但是平常使用如何指定DataDir? 以便将数据存放指定文件夹方便同步数据？ 是建立快捷方式,快捷方式中使用对应`--user-data-dir`参数？


The primary goal of the Chrome++ project is to provide a portable Chrome environment. By default, the program sets the data path to %app%\..\Data (as shown in the example from the .ini file; if left blank, this is also the default path). This is achieved by adding a launch parameter and meets the needs of most standard users seeking a portable version of Chrome. When data_dir is set to none, Chrome++ will not add the related launch parameter. This is clearly explained in the .ini file documentation.

If you want to set a custom data directory, you can modify the data_dir in the .ini file following the specified format (the recommended method) or set data_dir to none and use other methods to add the launch parameter. Please note that in order to achieve portability, Chrome++ introduces some modifications to the original Chrome, which may not be suitable for use as a debugging environment.
