### ISSUE TITLE
[Bug] 启动时用命令行参数传入--user-data-dir=***指定用户数据目录无效

### ISSUE THREAD

**Issue by eillel** [Bush2021/chrome_plus#128]
### 验证步骤

- [X] 我仔细看过 [INI 配置文件](https://github.com/Bush2021/chrome_plus/blob/main/src/chrome%2B%2B.ini) 并理解了每个配置项的作用。
- [X] 我未在 [Issue Tracker](https://github.com/Bush2021/chrome_plus/issues) 中寻找过我要提出的问题。
- [X] 我提供了可用于重现我报告的错误的最简配置。
- [X] 我确保使用中文描述问题。

### 版本信息

![image](https://github.com/user-attachments/assets/ca133ac0-1fcd-4caa-b923-04b861e816c4)

### 配置文件

```yaml
[general]
data_dir=%app%\..\Data
cache_dir=%app%\..\Cache

command_line=--no-first-run --disable-logging --disable-breakpad --no-report-upload --disable-features=PrintCompositorLPAC --force-renderer-accessibility=basic
boss_key=
translate_key=
show_password=1
win32k=0

[tabs]
double_click_close=1
right_click_close=0
keep_last_tab=1
wheel_tab=1
wheel_tab_when_press_rbutton=1
open_url_new_tab=0
open_bookmark_new_tab=1
new_tab_disable=1
new_tab_disable_name="about:blank","新建标签"
```

### 描述

做测试时我需要开启多个不同运行环境的浏览器窗口，所以在命令行窗口执行：
chrome.exe --in-process-plugins --user-data-dir="D:\Program Files\Google\ChromeData1"
但是在新版本中（Chrome++1.11.0版）这个参数无效，浏览器启动后用户目录总是会指定到%app%\..\Data下
将Chrome++恢复到1.7.3版本，使用同样的启动方式就能够将用户目录指定到ChromeData1

**Comment by Bush2021** [comment]
https://github.com/Bush2021/chrome_plus/issues/127#issuecomment-2516098389

**Comment by eillel** [comment]
> [#127 (comment)](https://github.com/Bush2021/chrome_plus/issues/127#issuecomment-2516098389)

Alright, thank you very much.
