### ISSUE TITLE
[Bug] 双击关闭标签在存在未活跃的、打开DevTools并且将其悬浮为新窗口的标签时失效

### ISSUE THREAD

**Issue by lamprose** [Bush2021/chrome_plus#132]
### 验证步骤

- [X] 我仔细看过 [INI 配置文件](https://github.com/Bush2021/chrome_plus/blob/main/src/chrome%2B%2B.ini) 并理解了每个配置项的作用。
- [X] 我未在 [Issue Tracker](https://github.com/Bush2021/chrome_plus/issues) 中寻找过我要提出的问题。
- [X] 我提供了可用于重现我报告的错误的最简配置。
- [X] 我确保使用中文描述问题。

### 版本信息

![image](https://github.com/user-attachments/assets/11a080dc-a1fe-4d6d-aeba-948e658009a5)

### 配置文件

```yaml
[general]
data_dir=%app%\..\..\Data
cache_dir=%app%\..\..\Cache
command_line=
launch_on_startup=
kill_launch_on_exit=0
launch_on_exit=
boss_key=
translate_key=
show_password=1
win32k=0

[tabs]
double_click_close=1
right_click_close=0
keep_last_tab=1
wheel_tab=1
wheel_tab_when_press_rbutton=1
open_url_new_tab=0
open_bookmark_new_tab=0
new_tab_disable=1
new_tab_disable_name="about:blank","新建标签"
```

### 描述

当Chrome浏览器存在未活跃的、打开DevTools并且将其悬浮为新窗口![image](https://github.com/user-attachments/assets/c0079d4e-5a57-433e-9920-ffb259ca05a8)的标签时   其他标签就无法通过双击关闭

**Comment by Bush2021** [comment]
Chrome++ 使用 IAccessible 来判断鼠标是否在标签上：https://github.com/Bush2021/chrome_plus/blob/9b3f7d498b7d5eb2563c3962f93a92e7df1aebd9/src/iaccessible.h#L284

在你描述的情境中，对应元素并不会按照预期展现，这可能是该情境下 Chromium 特殊的渲染方式导致的。因此，Chrome++ 无法判断其为标签，也就没有执行关闭操作。

我不认为这是一个 Bug，且我也很难一个好的方法来优化它。
