### ISSUE TITLE
[Feature] Master switch to enable/disable tab feature

### ISSUE THREAD

**Issue by MagicalDrizzle** [Bush2021/chrome_plus#133]
### Verification Steps

- [X] I have carefully read the [INI configuration file](https://github.com/Bush2021/chrome_plus/blob/main/src/chrome%2B%2B.ini) and understand the function of each configuration item.
- [X] I have not searched for the feature request I want to propose in the [Issue Tracker](https://github.com/Bush2021/chrome_plus/issues) and did not find it.
- [X] I am willing to create a pull request to implement the feature I proposed, otherwise I understand that the issue is likely to be closed.
- [X] I make sure to describe the feature in English.

### Description

It'd be nice to be able to use chrome++ purely as a portable profile creator and not have it mess with other browser defaults, like tabs handling. It doesn't seem to be possible to just delete the tab section in the config since chrome++ will just use the default settings - so you currently have to modify the tab settings to match the default behavior if you want the browser default.
So I think it would be nice to have a master ini key for enabling/disabling tab enhancement features - like `tab_enhancement: 0/1` maybe? If the key is 0 then none of the keys in `[tabs]` should apply and browser default behavior is kept.

**Comment by Bush2021** [comment]
I understand that the configuration file might be bloated right now, but actually, you just need to set all the options under [tabs] to 0 to use the browser's default tab behavior. Isn't that not too troublesome?

**Comment by MagicalDrizzle** [comment]
oh it is? I actually didn't realize all 0 is the default, thank you!
