### ISSUE TITLE
是否可以添加去掉主页的最近浏览图标？

### ISSUE THREAD

**Issue by mpamxl** [Bush2021/chrome_plus#14]
之前可以通过解包pak修改，但83版本后工具解包不出来了，可否通过Chrome++修改去掉最近浏览网址图标？

**Comment by Bush2021** [comment]
抱歉，我只会尽可能处理软件 Bug，不打算继续添加新功能。

**Comment by mpamxl** [comment]
但主页显示最近浏览网址也没法关闭，其实就是在pak里找到most-visited添加style="display: none;"即可，但现在pak工具没更新导致新版资源解包不完整，可否考虑在pakpatch中加入这个？也不算是添加太多功能，相比转成ini设置应该简单些吧？

**Comment by Bush2021** [comment]
> 但主页显示最近浏览网址也没法关闭，其实就是在pak里找到most-visited添加style="display: none;"即可，但现在pak工具没更新导致新版资源解包不完整，可否考虑在pakpatch中加入这个？也不算是添加太多功能，相比转成ini设置应该简单些吧？

![image](https://github.com/Bush2021/chrome_plus/assets/79072750/b3fd6514-331b-4534-a9c8-08512ca51c47)

@mpamxl 你指的是新标签页吧，我刚看了一下，右下角自定义 Chrome 是可以设置是否显示的。
