### ISSUE TITLE
[feature] 新标签页打开书签的实现

### ISSUE THREAD

**Issue by Ritchie1108** [Bush2021/chrome_plus#20]
只要处理 Chrome_WidgetWin_1 或者 Chrome_WidgetWin_2 两个 hwnd 底下递归检查 ROLE_SYSTEM_PUSHBUTTON 或者 ROLE_SYSTEM_MENUITEM, 然后判断鼠标在范围内, 根据获取到的 description 做一下简单的 url 判断就可以了

**Comment by Bush2021** [comment]
看起来是个不错的办法！我抽空看看，也欢迎你直接 Pr。

**Comment by Bush2021** [comment]
我目前算是初步实现了，不过有个判断是否为新标签页的逻辑还有点问题。你可以看一下我现在的实现方法和你有什么不同吗？

**Comment by Bush2021** [comment]
> 从 Chrome_RenderWidgetHostHWND 里取 ROLE_SYSTEM_DOCUMENT 的 value 来判断是不是 "chrome://new-tab-page" 会不会简单一点? 比较麻烦的是一些新标签页的扩展, value 的值可能只能是匹配 "chrome-extension://" 前缀加上 "newtab" 的模糊匹配这样的规则来处理了

其实我现在的判断应该没有大问题，新建标签那个按钮的 Name 和新标签页是一样的，这样写也可以解决语言问题，应该能匹配大多数情况。

现在主要是点击书签文件夹展开的那个菜单栏不在 TopContainerView 里面，所以这时候无法正确判断当前是否为新标签页，我不知道是不是我书签那个逻辑写的有问题。

**Comment by parademovie** [comment]
另一个思路是把书签的打开方式强制替换为 `ctrl+鼠标左键`，也就是说：
原版chrome：用户 `左键` 点击书签时，效果为在 `前台当前页打开网址`；用户 `ctrl+左键` 点击书签时，效果为在 `后台新标签页打开网址`。
修改后的效果：用户 `左键` 点击书签 或者  `ctrl+左键` 点击书签时，效果都为在 `后台新标签页打开网址`。
当然以上是一个选项，不需要的可以不开启。
解决方案可以是：
1.判断对书签的打开方式，把`左键`替换为`ctrl+左键`，类似[ahk的按键替换](https://wyagd001.github.io/v2/docs/misc/Remap.htm)。
2.无论哪种打开方式，把书签打开后的效果都变成  `ctrl+左键` 的效果，即为 `后台新标签页打开网址`，如果是书签文件夹，则保证文件夹窗口点击后不消失。

**Comment by Bush2021** [comment]
> 这个问题我在写的时候碰到过, 我本地是在 Chrome_WidgetWin_2 里, 但是其他人又是正常的 Chrome_WidgetWin_1 所以你要取 TopContainerView 的话, 你那边传的 hwnd 可以用 GetFocus() 来传进去

抱歉回复迟了。

我现在这个问题应该不是 Chrome_WidgetWin_ 不一样导致的吧，这个也可以在前面匹配的时候改成用 wcsstr 匹配通用字符串。

现在是这俩书签在新标签打开的功能单独使用都是正常的，但是如果还要判断新标签页的话文件夹那个就会有问题，我测试 GetFocus() 好像没能解决，感觉是点击文件夹之后导致 hwnd 变了，就无法正确判断了。

> name判断会有个问题, 如果用了标签页扩展, ROLE_SYSTEM_PAGETAB 的 name 和"新建标签页按钮"的 name 不一定会相同

我试了 ITab 和 Infinity 都正常，你用的标签页扩展是？

**Comment by Bush2021** [comment]
> 另一个思路是把书签的打开方式强制替换为 `ctrl+鼠标左键`，也就是说： 原版chrome：用户 `左键` 点击书签时，效果为在 `前台当前页打开网址`；用户 `ctrl+左键` 点击书签时，效果为在 `后台新标签页打开网址`，如果打开的是书签文件夹，则保证文件夹弹出窗口点击后不消失。
> 
> 修改后的效果：用户 `左键` 点击书签 或者 `ctrl+左键` 点击书签时，效果都为在 `后台新标签页打开网址`。 当然以上是一个选项，不需要的可以不开启。 解决方案可以是： 1.改变书签的打开方式。 判断对书签的打开方式，把`左键`替换为`ctrl+左键`，类似[ahk的按键替换](https://wyagd001.github.io/v2/docs/misc/Remap.htm)。 2.改变书签打开后的效果。 无论哪种打开方式，把书签打开后的效果都变成 `ctrl+左键` 的效果，即为 `后台新标签页打开网址`，如果打开的是书签文件夹，则保证文件夹弹出窗口点击后不消失。

不是很明白你的意思。

原版效果是左键单击在当前页打开，Ctrl+左键（或直接中键）在后台打开，Shift+中键在前台打开。我修改的方法就是发送 Shift+中键实现在前台打开标签页。所以你说的方式和我的只有打开方式不同吧？

**Comment by parademovie** [comment]
> 不是很明白你的意思。
原版效果是左键单击在当前页打开，Ctrl+左键（或直接中键）在后台打开，Shift+中键在前台打开。我修改的方法就是发送 Shift+中键实现在前台打开标签页。所以你说的方式和我的只有打开方式不同吧？

你好，你说的没错，就是打开方式不同。
另外建议再增加一个 发送 Ctrl+左键  实现  后台新标签页打开。比如`Ctrl_click_open_bookmark=1`

这样的好处在于：当书签栏有文件夹时，**左键点击**打开该文件夹里的某个书签时，你会发现该书签会在 后台新标签页打开 ，而同时 该文件夹的**弹窗不消失**，这时你就可以**连续多次左键点击打开**该文件夹里的 其他的 更多的 你喜欢的 书签了。
而这些书签都会在 后台新标签页打开，不影响当前页面 用户正在浏览的内容。

所以感觉会很实用，而且更有效率。感谢🙏

**Comment by pengweiqhca** [comment]
我的书签栏只会有新建的标签时才会显示，所以和这个需求实现是一样的啊。
