### ISSUE TITLE
新标签页的问题请教..

### ISSUE THREAD

**Issue by moxuexue** [Bush2021/chrome_plus#22]
大神问下
新建前台标签页打开地址栏输入的内容
新建前台标签页打开书签
这俩是不是不好使? 我测试不行啊? 感谢!

**Comment by Bush2021** [comment]
只是提交了代码，但因为这俩功能和 #20 有冲突，所以还没发版。

**Comment by moxuexue** [comment]
> 只是提交了代码，但因为这俩功能和 #20 有冲突，所以还没发版。

我就说呢..好呢 非常期待这俩功能 感谢! 另外不搞个群啥的吗 大神...

**Comment by Bush2021** [comment]
不是大神，只是有空研究一下而已，我也不能保证任何功能以及后续维护，所以群还是算了。
