### ISSUE TITLE
【1.71】 120.0.6099.71，昨天开始，顶部菜单栏变成蓝色，增加了背景模式？？？

### ISSUE THREAD

**Issue by kakapas** [Bush2021/chrome_plus#28]
用的是这里解压的离线安装包
https://chrome.noki.eu.org/

只要挂一次魔法，就会更新界面
是不是1.71阻止chrome更新出问题呢？

请核查~

更新后的界面如下：
![1 71](https://github.com/Bush2021/chrome_plus/assets/125766482/54c00107-1ea4-4d5a-a985-8132114eefb1)

更新前的界面是这样的
顶部默认色，箭头在右边，没有界面设置
如下：

![1 712](https://github.com/Bush2021/chrome_plus/assets/125766482/4bbd6196-0f21-4247-a419-a53dfed736e7)

**Comment by shuaiyewl** [comment]
谷歌更新Chrome 的UI 并不一定需要更新Chrome版本的。
