### ISSUE TITLE
改进建议,是否可以把地址栏右键菜单列表的第一个改为粘贴并搜索

### ISSUE THREAD

**Issue by freedomspiritJohn** [Bush2021/chrome_plus#29]
这样方便直接进行搜索
![image](https://github.com/Bush2021/chrome_plus/assets/129288685/4b96b768-26ed-4a65-96c5-f63733e27f14)
像这个就需要往下滑很多列表才能进行搜索
![image](https://github.com/Bush2021/chrome_plus/assets/129288685/50f84358-a933-4d17-a3e5-3d77cfea135d)

**Comment by Bush2021** [comment]
改不了。
