### ISSUE TITLE
是不是不兼容edge了

### ISSUE THREAD

**Issue by visiLi** [Bush2021/chrome_plus#30]
如题，无论是新版edge还是旧版，都不行。求解决教程

**Comment by shuaiyewl** [comment]
注意：Edge 需要 setdll强制注入dll

**Comment by Heporis** [comment]
目前123版强制注入后，还能正常使用，但是追加 Chromium 启动参数，会导致edge新标签页的内容无法关闭，大概是--no-first-run，具体哪条没测试。
开始我还以为是edge123版的bug，发反馈diss了人家是流氓，怪不得干不过chrome😅
