### ISSUE TITLE
有三种情况未在新标签打开

### ISSUE THREAD

**Issue by SoVieTing** [Bush2021/chrome_plus#31]
首先已开启了：
```
open_url_new_tab=1
open_bookmark_new_tab=1
new_tab_disable=1
```
1.当前已打开了网页。如果点击的书签是下面这种，则不会在新标签打开:
```
chrome://chrome-urls
chrome://settings/content/all
```
2.当前已打开了网页。如在书签文件夹中，有名称为**1-XXX**的书签，点开文件夹后按1就可以打开他。但是没有在新标签打开。
3.在地址栏鼠标右键**粘贴并搜索*****，没有在新标签打开。

虽然已经很好用了，如能实现这三种新标签打开就更棒了。

**Comment by liangxyz** [comment]
我是.在地址栏鼠标右键粘贴并转到***，没有在新标签打开。

**Comment by Bush2021** [comment]
1. 这个好解决，加个判断就可以；
2. 书签在新标签页打开的触发条件是鼠标左键单击，所以键盘操作不会触发，因为我没用过你说的这种方式，所以应该不会去做额外处理；
3. 这个不好处理，因为 “粘贴并*” 这个按钮本身不支持结合其它按键，从而实现在新标签页打开，所以建议还是手动回车吧。

**Comment by SoVieTing** [comment]
@Bush2021 能解决第一个就很棒！感谢。
@liangxyz 剪切板里是文本，显示为粘贴并搜索；剪切板里是链接，显示为粘贴并转到。
