### ISSUE TITLE
快捷键关闭标签页太快时不能保留最后一个标签页

### ISSUE THREAD

**Issue by Celestialsapien** [Bush2021/chrome_plus#32]
例如剩下两个标签页，如果按ctrl+w+w间隔过短时，会直接退出浏览器，没法保留一个新标签页。
大佬有没办法解决？

**Comment by Bush2021** [comment]
这个问题很久以前就存在吧；

我想应该是目前的判断方法需要先遍历节点，这个速度比较慢的原因，不是很好解决；

一个可能的方法是劫持所有 ctrl+w 的操作，然后给 Chrome++ 足够的时间来判断并发送指令，缺点就是可能会有一定的延迟感，我有空研究一下吧。

**Comment by Celestialsapien** [comment]
好的大佬

**Comment by SoVieTing** [comment]
@Celestialsapien 是有这问题。确实需要确保不退出的话，可以装这个扩展解决https://chromewebstore.google.com/detail/dont-close-window-with-la/dlnpfhfhmkiebpnlllpehlmklgdggbhn。
@Bush2021 不要延迟感！不要延迟感！不要延迟感！😱

**Comment by Celestialsapien** [comment]
@SoVieTing 好的
我看到消息edge正准备把保留最后标签页功能（点x也保留）内置，最快在下月底实装，但是现在往edge注入dll失效了，不知以后能不能修复

**Comment by Bush2021** [comment]
> @Celestialsapien 是有这问题。确实需要确保不退出的话，可以装这个扩展解决https://chromewebstore.google.com/detail/dont-close-window-with-la/dlnpfhfhmkiebpnlllpehlmklgdggbhn @Bush2021 不要延迟感！不要延迟感！不要延迟感！😱

既然扩展完美能解决，那我就不管了吧~

**Comment by Bush2021** [comment]
> @SoVieTing 好的 我看到消息edge正准备把保留最后标签页功能（点x也保留）内置，最快在下月底实装，但是现在往edge注入dll失效了，不知以后能不能修复

注入应该不会失效，便携在117版本之后失效了，不知道是什么原因；

如果扩展可以解决的话建议使用扩展，这个 issue 我先关了哈。
