### ISSUE TITLE
有些页面排版会不正确

### ISSUE THREAD

**Issue by yanshibin** [Bush2021/chrome_plus#33]
https://free.aliyun.com/
<img width="1289" alt="image" src="https://github.com/Bush2021/chrome_plus/assets/18375162/1ef688a2-f28c-4b64-9a81-5f826b3d47b9">
如果暂时关闭chrome_plus 显示就正常

**Comment by Bush2021** [comment]
我这里正常，说明和 Chrome++ 无关，检查是不是你扩展冲突了。
