### ISSUE TITLE
MouseInc会影响右键关闭标签页的使用

### ISSUE THREAD

**Issue by qixiaoshu** [Bush2021/chrome_plus#34]
chrome++在MouseInc打开的情况下，右键关闭标签页需要双击两次。如果将chrome.exe加入MouseInc的排除列表就可以解决问题。但是，MouseInc很好用，想要在MouseInc不屏蔽chrome的情况下，使用chrome++的右键关闭标签页。

**Comment by Bush2021** [comment]
软件优先级更高，这个我没什么好办法。

**Comment by dianso** [comment]
等等吧，那个作者好像还在坐牢了
