### ISSUE TITLE
多profile下似乎有问题

### ISSUE THREAD

**Issue by userzzzq** [Bush2021/chrome_plus#35]
有多个profile时，点击右上角的头像，出现了重复的账号ID。
内核版本：121.0.6167.140。（不用chrome++则无此问题）

![11](https://github.com/Bush2021/chrome_plus/assets/69742519/b0bde993-6637-4cce-9619-2f476b01583e)

**Comment by Bush2021** [comment]
无法复现，且我认为不是  Chrome++ 的问题，可尝试自行删除 Data\Profile 2 之类的文件夹。
