### ISSUE TITLE
大佬有没有兴趣加一个多列书签

### ISSUE THREAD

**Issue by flatchoysum** [Bush2021/chrome_plus#42]
多列书签，顾名思义，当点击书签文件夹时，其中所有书签平整地铺开，举目千里，一览无余，豁然开朗，心旷神怡，游目骋怀，目不暇接，美不胜收，怡然自得，想点哪个点哪个😄
这个老大有兴趣吗？
![dlsq1](https://github.com/Bush2021/chrome_plus/assets/130772140/50e98bcc-7fa8-4859-9828-af3ac9133da0)

**Comment by Bush2021** [comment]
这个 Chrome++ 做不了的。
