### ISSUE TITLE
能否加个选项，后台打开标签页？

### ISSUE THREAD

**Issue by drw2005** [Bush2021/chrome_plus#43]
插件很好用，非常感谢，顺便提个小建议：
能否加个选项，后台打开标签页？包括点击链接、地址栏输入、书签打开等。

**Comment by Bush2021** [comment]
下个版本支持后台打开书签和地址栏输入内容，页面内链接做不了，可以用扩展或脚本实现。

**Comment by drw2005** [comment]
> 下个版本支持后台打开书签和地址栏输入内容，页面内链接做不了，可以用扩展或脚本实现。

非常好用，感谢大佬这么快就反馈！
