### ISSUE TITLE
更换电脑后无法同步数据

### ISSUE THREAD

**Issue by wgetnz** [Bush2021/chrome_plus#44]
复现步骤

在A电脑上正常登录chrome，同步数据（有同步密码），同步后，将所有数据复制到B电脑，打开后，发现插件，书签等数据都在，但是账号显示未登录，同步已暂停，手动重新登录，输入同步密码，同步后关掉浏览器，重新打开，发现还是提示未登录，陷入死循环
![2024-03-15_16-39-18](https://github.com/Bush2021/chrome_plus/assets/62410571/1c10b68f-3e79-4739-a02c-d28cc5444b99)

**Comment by Bush2021** [comment]
复现不了，也没见有别的用户反馈这个问题。
