### ISSUE TITLE
1.8.2版偶发点击书签无反应

### ISSUE THREAD

**Issue by leungxt** [Bush2021/chrome_plus#45]
chorme版本：122.0.6261.70
chorome++版本：1.8.2
已设置为open_bookmark_new_tab=1
从书签栏点开书签，会偶发失效，表现为：不会在当前页打开，也不会在新建标签页打开。
重启浏览器能解决此问题，但是过一会有会出现此情况。

**Comment by Bush2021** [comment]
是不是点击书签的同时按住了 ctrl 或者 shift？

**Comment by ace115** [comment]
同样的问题

**Comment by ace115** [comment]
同样的问题，没有按住键

**Comment by Bush2021** [comment]
我始终无法复现你们的问题。请提供最小可复现配置。

**Comment by leungxt** [comment]
怀疑是某个扩展造成的，先把rsshub rader关了似乎就好了，我再继续观察下

> 我始终无法复现你们的问题。请提供最小可复现配置。

**Comment by leungxt** [comment]
再补充一点哈，书签栏失效的同时，地址栏新开标签也会失败...

> chorme版本：122.0.6261.70 chorome++版本：1.8.2 已设置为open_bookmark_new_tab=1 从书签栏点开书签，会偶发失效，表现为：不会在当前页打开，也不会在新建标签页打开。 重启浏览器能解决此问题，但是过一会有会出现此情况。

**Comment by Bush2021** [comment]
你先排除你的环境干扰再说，把鼠标手势、快捷键之类的软件关掉，新建一个配置文件用一段时间。你现在的说法我确定不了是不是 Chrome++ 的问题。
