### ISSUE TITLE
【功能请求】希望能添加鼠标悬浮标签页自动激活标签功能

### ISSUE THREAD

**Issue by liangxyz** [Bush2021/chrome_plus#47]
如题，我感觉这个功能是懒人的福音，请问作者能不能添加进来呢？
就是把鼠标放在标签页上，会自动激活悬停的标签页面

**Comment by Bush2021** [comment]
我不打算做这个功能，因为我自己用不到且这个功能使用逻辑破坏了原生体验。不过欢迎 PR。
