### ISSUE TITLE
改进自定义网页翻译快捷键

### ISSUE THREAD

**Issue by Heporis** [Bush2021/chrome_plus#49]
按下快捷键会在地址栏弹出是否翻译的弹窗，还需要点一下才能翻译。可以调用鼠标右键菜单里的”翻译为中文（简体）“，直接一步到位吗？

**Comment by Bush2021** [comment]
现在预期的效果就是一步到位的。

**Comment by Heporis** [comment]
不好意思，chrome确实是一步到位，edge还要再确认一下😅
