### ISSUE TITLE
最新版chrome/edge的无痕模式中new_tab_disable失效

### ISSUE THREAD

**Issue by Heporis** [Bush2021/chrome_plus#51]
测试浏览器版本：chrome/edge 123.0

第一种情况：
操作步骤：
打开无痕模式，从地址栏下面的收藏夹栏中打开一个书签，会新建一个标签页打开网站并且不会自动切换到那个标签页，如下面图中所示。

第二钟情况：
操作步骤：
打开无痕模式，手动新建标签页，从地址栏下面的收藏夹栏中打开一个书签，会新建一个标签页打开网站并自动切换到那个标签页，图略。

第三种情况：
操作步骤：
打开无痕模式，不论是否手动新建标签页，地址栏输入网址回车，都会新建一个标签页打开网站并自动切换到那个标签页，图略。

第四种情况：
操作步骤：
edge汉堡菜单，收藏夹选项，右键选择“在工具栏中显示”，打开无痕模式，从右上角收藏夹中打开网站，此时new_tab_disable正常工作。
由于chrome没有在工具栏中显示收藏夹的功能，类似的操作是，打开无痕模式，汉堡菜单，书签和清单，打开一个网站，会新建一个标签页打开网站并自动切换到那个标签页，图略。

![GIF 2024-3-30 14-17-19](https://github.com/Bush2021/chrome_plus/assets/51895154/c6d2fe85-3514-4fee-8aa9-6e76d57db51b)
![GIF 2024-3-30 14-20-43](https://github.com/Bush2021/chrome_plus/assets/51895154/d83ad03e-8e28-477b-9045-099ab996afb2)

**Comment by Bush2021** [comment]
下个版本会修复这个问题，不过需要添加启动参数  `--force-renderer-accessibility`。

**Comment by Bush2021** [comment]
请尝试 1.8.3 版本。

**Comment by Heporis** [comment]
chrome可以了，edge还是一样

**Comment by Bush2021** [comment]
> chrome可以了，edge还是一样

谁告诉你兼容 Edge 了吗？这次还添加了自定义新标签的名称，你非要用不会去试试这个吗？

**Comment by Heporis** [comment]
前面试过了，但是可能名称不对，没成功，以为是不支持。😅
又试了好多，发现自定义新标签名称和浏览器的显示语言也相关，不过InPrivate是不变的，所有语言都可以用。
如果下次更新的话，可以把InPrivate添加到内置列表吗？

**Comment by Bush2021** [comment]
> 前面试过了，但是可能名称不对，没成功，以为是不支持。😅 又试了好多，发现自定义新标签名称和浏览器的显示语言也相关，不过InPrivate是不变的，所有语言都可以用。 如果下次更新的话，可以把InPrivate添加到内置列表吗？

Edge 进行了大量魔改，包括修改了很多 Chromium 的命名，无痕模式这个问题也是命名不匹配导致的，所以我才做了这个自定义新标签名称；

正因为此，我才说只会考虑兼容 Chrome 最新稳定版，Edge 能不能用只能随缘。

**Comment by Heporis** [comment]
好的
