### ISSUE TITLE
右键翻译网页后点击弹出的窗口会导致浏览器闪退

### ISSUE THREAD

**Issue by ace115** [Bush2021/chrome_plus#54]
貌似是1.8.3才出现的问题，用隐身模式禁用所有扩展后测试问题依旧。
![屏幕截图 2024-04-05 222605](https://github.com/Bush2021/chrome_plus/assets/16514550/54183ac5-84fe-4554-8385-0390bcd9927a)

**Comment by Bush2021** [comment]
1. 没有贴出配置
2. 没有动图演示效果
3. 我复现不了

**Comment by shuaiyewl** [comment]
我也遇到了这个bug

Chrome++ 1.8.3 下使用Chrome内置的网页翻译按钮就会造成Chrome闪退（如果设置 new_tab_disable=0  也能避免闪退）

换回 Chrome++ 1.8.2 无此问题（在1.8.2下 无论设置 new_tab_disable=0或是1 都不会闪退）

具体来说就是对翻译按钮里的“英文”和“中文”标签进行点击操作就会造成闪退。

**Comment by shuaiyewl** [comment]
补充说明：Chrome++ 1.8.3下
open_bookmark_new_tab=1
new_tab_disable=1
这俩项同时开启，使用翻译按钮时就会闪退
