### ISSUE TITLE
看Youtube视频时切换回非全屏模式时闪退

### ISSUE THREAD

**Issue by leungxt** [Bush2021/chrome_plus#55]
![image](https://github.com/Bush2021/chrome_plus/assets/51778432/2d3270e9-c4e8-4c09-9baa-6c27a155632c)

Chrome版本 123.0.6312.106（正式版本） （64 位）

[Chrome++]1.8.3 modified version

看youtube视频时，点击右下角全屏后，再次点击全屏按钮切换成非全屏模式时Chrome闪退。1.8.3下测试了腾讯视频、优酷、爱奇艺，不会发现闪退。关闭了所有扩展程序后，依然会闪退。

切回1.8.2版测试，也没有出现闪退。

**Comment by Bush2021** [comment]
复现不了，自己先排查一下是 Chrome++ 哪一个配置导致的问题再反馈。

**Comment by leungxt** [comment]
> 复现不了，自己先排查一下是 Chrome++ 哪一个配置导致的问题再反馈。

网址：https://www.youtube.com/watch?v=QgyQlyRaG04
Chrome版本 123.0.6312.106（正式版本） （64 位）
[Chrome++] 1.8.3 modified version

double_click_close=1
right_click_close=0
keep_last_tab=1
wheel_tab=1
wheel_tab_when_press_rbutton=1
open_url_new_tab=0
open_bookmark_new_tab=0
new_tab_disable=1
new_tab_disable_name="about:blank","新建标签"

测试了，用以上配置，不闪退




double_click_close=1
right_click_close=0
keep_last_tab=1
wheel_tab=1
wheel_tab_when_press_rbutton=1
open_url_new_tab=1
open_bookmark_new_tab=1
new_tab_disable=1
new_tab_disable_name="about:blank","新建标签"

用以上配置，必闪退

**Comment by Bush2021** [comment]
测试一切正常，我就不在这里继续追问了，你找到问题是什么再开一个 issue 吧。
