### ISSUE TITLE
右键翻译网页后点击弹出的窗口会导致浏览器闪退

### ISSUE THREAD

**Issue by ace115** [Bush2021/chrome_plus#56]
![屏幕截图 2024-04-06 120155](https://github.com/Bush2021/chrome_plus/assets/16514550/128b95c0-5abe-406f-ac9a-e2d14c211b68)
配置设置为open_bookmark_new_tab=1时会出现
![12c15b18-6579-4036-973e-e86c0f276cf3](https://github.com/Bush2021/chrome_plus/assets/16514550/62f912a8-51e8-4e9a-8483-16008ad96f4a)

**Comment by Bush2021** [comment]
确实有 Bug，不过你可以测试下，这问题是 new_tab_disable=1 时才导致的，为 0 是没问题的。

**Comment by Bush2021** [comment]
[version.zip](https://github.com/Bush2021/chrome_plus/files/14894312/version.zip)

可以测试一下上面这个。没有问题的话下个版本会修复这个问题。

**Comment by leungxt** [comment]
> [version.zip](https://github.com/Bush2021/chrome_plus/files/14894312/version.zip)
> 
> 可以测试一下上面这个。没有问题的话下个版本会修复这个问题。

有效，不闪退了。我之前反馈的youtube切换非全屏闪退的问题也解决了

**Comment by shuaiyewl** [comment]
open_bookmark_new_tab=1
new_tab_disable=1
是这俩设置项同时都是1 才能复现此bug
