### ISSUE TITLE
新建前台标签页打开书签，偶尔会在后台打开

### ISSUE THREAD

**Issue by Heporis** [Bush2021/chrome_plus#57]
试了好多次，随机出现😅
chrome 123.0.6312.106

**Comment by Heporis** [comment]
![GIF 2024-4-7 1-46-37](https://github.com/Bush2021/chrome_plus/assets/51895154/8f01cac6-d4dc-4b5d-af75-c514c6b12ee6)

**Comment by Bush2021** [comment]
复现不了，你一句 “随机出现” 不能说明任何问题，动图也无法判断是 Chrome++ 的问题。自己先排查一下是 Chrome++ 哪一个配置导致的问题再反馈。
