### ISSUE TITLE
用鼠标手势关闭标签时，最后一个标签也会关闭

### ISSUE THREAD

**Issue by lgw1860** [Bush2021/chrome_plus#59]
Chrome 最新版，Chrome++升级到1.8.4后，用鼠标手势（MouseInc 2.13.4）关闭标签时，最后一个标签也会关闭，在Chrome++.ini 配置文件中看了一下 keep_last_tab=1，改成0，再改回来，还是会关闭最后一个标签。Chrome++换回1.8.3 鼠标手势就是正常的。不知道是不是个例，或者是MouseInc的问题。

**Comment by Bush2021** [comment]
[version-alpha-536f959.zip](https://github.com/Bush2021/chrome_plus/files/14926336/version-alpha-536f959.zip)

试试这个版本。

**Comment by lgw1860** [comment]
> [version-alpha-536f959.zip](https://github.com/Bush2021/chrome_plus/files/14926336/version-alpha-536f959.zip)
> 
> 试试这个版本。

这个版本是可以的，CTRL+F搜索也正常了，不会全屏了。
