### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by archibaldiys** [Bush2021/chrome_plus#60]
Hello

I transferred my profile (the entire "Default" folder to C:\ChromeDll\Data\Default) but Chrome did not see my profile, what is the problem and how to fix it?

Only the bookmarks were transferred(

**Comment by Bush2021** [comment]
> Portable design: the program is placed in the App directory, and data is stored in the Data directory (incompatible with the original data; you can reinstall the system or change computers without losing data).

https://github.com/Bush2021/chrome_plus?tab=readme-ov-file#features
