### ISSUE TITLE
打开字符多的网页会导致网页卡死

### ISSUE THREAD

**Issue by ace115** [Bush2021/chrome_plus#62]
chrome 124.0.6367.61
Chrome++ 1.8.5
比如 这个网页 https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/ChinaMax/ChinaMax_Domain.yaml 在不启用chromeplus的情况下就是正常的

**Comment by Itzamana** [comment]
![image](https://github.com/Bush2021/chrome_plus/assets/20204389/758c9c8e-f0f5-4f67-a7e4-2a6c9b865060)

没有复现，不过这个网页确实占了很多内存…

**Comment by litianyuhehe** [comment]
https://github.com/Bush2021/chrome_plus/assets/29541117/45f381af-3721-4a4f-a41a-41bfd1887525

我试了一下，也是这样，chrome124.0.6367.61配chrome++1.8.5，chrome++配置为默认，系统win11 23h2 22635.3495，cpu13600kf，显卡amd6800xt

**Comment by litianyuhehe** [comment]
cpu占用会上升，网页会卡住无法下滑。

**Comment by litianyuhehe** [comment]
更新了chrome beta 125.0.6422.4 不卡了

**Comment by fangyuan99** [comment]
还是会有这个问题
