### ISSUE TITLE
supermium浏览器

### ISSUE THREAD

**Issue by xiaopangzi13140** [Bush2021/chrome_plus#64]
https://github.com/win32ss/supermium
最近这个supermium很火，也是基于Chromium内核，支持很多系统，包括Windows XP, 2003, Vista, 7 and 8.x，很厉害的样子。

试了一下win7用这个插件可行，xp不行。

**Comment by xiaopangzi13140** [comment]
xp浏览器可打开，但编写没有成功。

**Comment by shuaiyewl** [comment]
shuax早期的Chrome++ 都已经不再支持XP了，现在这个修改版更不会支持xp

**Comment by buzzed12** [comment]
supermium是支持ungoogle chromium的--disable-machine-id和--disable-encryption-win这两个功能，用命令行或者快捷方式开启就能让用户配置便携化，弊端是你的用户配置没有加密了
