### ISSUE TITLE
Can it be used on Thorium and Brave?

### ISSUE THREAD

**Issue by candrapersada** [Bush2021/chrome_plus#65]
Can full portable be used on Thorium and Brave?

**Comment by Bush2021** [comment]
Test it yourself

**Comment by molezz** [comment]
> Can full portable be used on Thorium and Brave?

yes, it can
look

<img width="451" height="321" alt="Image" src="https://github.com/user-attachments/assets/9f54eaec-99c2-49f2-91c3-8a8c8b53e80a" />

<img width="432" height="215" alt="Image" src="https://github.com/user-attachments/assets/82f73a79-a760-4ef7-b228-294de77e5c4e" />
