### ISSUE TITLE
建议增加右键点击的快捷功能

### ISSUE THREAD

**Issue by flatchoysum** [Bush2021/chrome_plus#67]
1.建议增加右键点击“新建标签”按钮的快捷功能

目前现状：
右键点击当前标签页右侧的 “新建标签”按钮（+ 按钮）时，弹出菜单，有“最小化”“打开新的标签页”等功能。
右键点击标签栏空白处，也可以有此弹出菜单。
所以增加一个 “右键+按钮”的功能，不影响弹出菜单。

今建议：
右键点击标签页右侧的 “新建标签”按钮（+ 按钮），执行以下操作：
如果剪贴板中是非网址（字符串），则自动 定位到地址栏（发送按键 `ctrl+L` 或者` alt+d`），自动执行 右键菜单的 粘贴并搜索“xxx”（发送按键 `ctrl+v`，回车）

ps：发送按键后可配置间隔时间500ms，配合 open_url_new_tab=1 效果更好。

如果剪贴板中是网址，则新建前台标签页，自动 定位到地址栏，自动执行 粘贴并转到“https://xxx/”。（发送的按键是一样的）

特别地，如果当前标签是新标签页，则就在此标签页打开 搜索结果 或 网址。

如果有了此功能，则是相当快捷方便的，办事效率会更快，事半功倍！

2.右键点击“扩展程序”按钮，能快捷打开：chrome://extensions/

3.第三个小建议是 左键单击 主页 按钮时，新建前台标签打开主页{ `SendKeys(VK_MBUTTON, VK_SHIFT);` }

最后祝您和您的家人五一节快乐！身体健康！万事如意 😄

**Comment by Bush2021** [comment]
1和3我觉得太个性化了，3说的主页是什么我都不知道，所以不打算做。

2倒是有合理性，不过实现起来我觉得不那么优雅，比如可能只有浏览器页面语言是中文才能生效，我不喜欢这样。如果要做的话，我觉得还不如搞成自定义快捷键。

**Comment by Bush2021** [comment]
另外我建议你们不要提 feature request，现在我能实现或者想实现的基本都实现了，新功能大概不会得到满足。

**Comment by KnIfER** [comment]
这点击啥的功能基本都能用AHK或者扩展实现。

比如点击书签前台打开（很久之前就有人提过，读取acc信息即可）。

比如保留最后一个标签页（有扩展实现）。

好钢要用在刀刃上。

**Comment by flatchoysum** [comment]
@KnIfER 
> 这点击啥的功能基本都能用AHK或者扩展实现。
> 
> 比如点击书签前台打开（很久之前就有人提过，读取acc信息即可）。
> 
请问这里的 “读取acc信息” 具体怎么操作，有什么教程或链接吗？

**Comment by KnIfER** [comment]
[Fixing Chrome: Address Bar and Bookmarks in new tab by default - AutoHotkey Community](https://www.autohotkey.com/boards/viewtopic.php?f=6&t=94568&p=419785&hilit=chrome+bookmark+new+tab#p419785)


[Chrome : 点击书签栏在新页面打开的完美解决方案！(AHK脚本分享) - 掘金](https://juejin.cn/post/7346798518361178175)

可以去AHK吧问问，AHK功能很强大，但需要自己调。

**Comment by flatchoysum** [comment]
> [Fixing Chrome: Address Bar and Bookmarks in new tab by default - AutoHotkey Community](https://www.autohotkey.com/boards/viewtopic.php?f=6&t=94568&p=419785&hilit=chrome+bookmark+new+tab#p419785)
> 
> [Chrome : 点击书签栏在新页面打开的完美解决方案！(AHK脚本分享) - 掘金](https://juejin.cn/post/7346798518361178175)
> 
> 可以去AHK吧问问，AHK功能很强大，但需要自己调。

感谢大佬🙏
