### ISSUE TITLE
Chromium 126.x - Error STATUS_DLL_INIT_FAILED

### ISSUE THREAD

**Issue by Uber-1** [Bush2021/chrome_plus#68]
The Chromium dev builds ( https://download-chromium.appspot.com/dl/Win ; https://download-chromium.appspot.com/dl/Win_x64 ) don't work with "version.dll". Error **STATUS_DLL_INIT_FAILED**
Screenshot: 
![2](https://github.com/Bush2021/chrome_plus/assets/148308766/2951e6cf-0b44-4ec8-8ebc-8ce6f055fb35)

**Comment by Bush2021** [comment]
![2024-05-04_202910](https://github.com/Bush2021/chrome_plus/assets/79072750/373ada77-8f4a-41a3-ba70-e1f5ada39637)

The official build of Chrome 126 worked fine.

Also, I will consider your issue invalid if you raise it without reading the document.

https://github.com/Bush2021/chrome_plus?tab=readme-ov-file#compatibility

**Comment by Uber-1** [comment]
Well...
You can just wait until Google merges all changes from Chromium to "master" of Chrome in some weeks. Then we will get the same  error on any Chrome 126.
Or you may try to find the reason of the problem now, when we have some time before the "bad 126 comes". Your wish.

This error acts the same way as that was on 118 version (with older dll versions by Shuax). Do you remember? The first bugs were found with this zip releases (versions of early dev of Chromium). Another browsers got the error some weeks later, just when they got update to the same 118 version.

Please, try that zip to check.
Now these Chromium dev still can work with "--no-sandbox" parameter. The same symptom of "118 problem". But can't work without "--no-sandbox" parameter.

**Comment by Bush2021** [comment]
Well, I guess that's because https://github.com/chromium/chromium/commit/5ea1f7034a8279c2e58226498a351c6220501149, which enabled `WinSboxNoFakeGdiInit`. I have no idea for what reason, this commit that was supposed to have been merged into Google Chrome Canary didn't work. Hence I assume the official build of Chrome Canary worked fine.

We are still not sure if this commit will reach the stable releases channel, therefore further observation is required. Anyway, thanks for letting me know.

**Comment by Uber-1** [comment]
I have no hope on Google. They like to spoil the browser. That is not the first time they make a problem for Chrome++ DLL.
Sorry, I am not a "big guru" of chromium sources, can't help.
I have also found that Vivaldi++ DLL also does not work there and wrote the same issue for **ca-x** (aka **czyt**) [here](https://github.com/ca-x/vivaldi_plus/issues/49). May be that would help for you both. Don't know... Need for another users to confirm the problem.

**Comment by Bush2021** [comment]
try https://github.com/Bush2021/chrome_plus/releases/tag/1.8.7-alpha

**Comment by Uber-1** [comment]
> try https://github.com/Bush2021/chrome_plus/releases/tag/1.8.7-alpha
Thanks. This works fine for me: 
![3](https://github.com/Bush2021/chrome_plus/assets/148308766/8958aab2-5483-4581-ac98-c846fc895b38)
