### ISSUE TITLE
right_click_close 启用，右键关闭tab似乎有bug

### ISSUE THREAD

**Issue by Echo1188** [Bush2021/chrome_plus#69]
环境：
![124-1 8 6](https://github.com/Bush2021/chrome_plus/assets/96213641/26630986-aff4-48a3-9596-7b538ee43e7a)
Chrome: 版本 124.0.6367.79（正式版本） （64 位）
Chrome++: 1.8.6

配置：
[tabs]
double_click_close=1
right_click_close=1
keep_last_tab=1
wheel_tab=1
wheel_tab_when_press_rbutton=0
open_url_new_tab=1
open_bookmark_new_tab=1
new_tab_disable=0
new_tab_disable_name="about:blank","新建标签"

---

问题描述：
1、假如我有tab 1, tab 2两个标签页，我用右键关闭 tab 2时，经常会同时关闭tab 1。(如下gif图)
![issue69record](https://github.com/Bush2021/chrome_plus/assets/96213641/3e4f77bf-78d9-4414-b451-5f7a16eb95ba)

2、这种情况主要发生在只有2个tab的时候，如果tab 1左边还有很多个tab页面，很少会遇到以上情况。
3、从1.8.2升上来的，1.8.2前没遇到过。

**Comment by Itzamana** [comment]
更新到稳定版124.0.6367.119试试？

**Comment by Bush2021** [comment]
https://github.com/Bush2021/chrome_plus/releases/tag/1.8.7-alpha

请测试 `version-alpha-2d42777.7z` 并反馈这个版本是否引入了新的 bug。

**Comment by YorkWaugh** [comment]
If possible, please help test whether this problem exists in this version.
[version.zip](https://github.com/Bush2021/chrome_plus/files/15229683/version.zip)

**Comment by Bush2021** [comment]
https://github.com/Bush2021/chrome_plus/releases/tag/1.8.7-alpha

`version-alpha-30b9594.7z` 直接测试这个吧

**Comment by Echo1188** [comment]
> https://github.com/Bush2021/chrome_plus/releases/tag/1.8.7-alpha
> 
> `version-alpha-30b9594.7z` 直接测试这个吧

这个测试右键关闭tab可以的，正常。
