### ISSUE TITLE
STATUS_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by lkeme** [Bush2021/chrome_plus#76]
![image](https://github.com/Bush2021/chrome_plus/assets/19500576/be2239e6-9d5d-42e1-9b2d-6fd017f2a4d0)

1.8.7 部分网页崩溃，1.8.6 一切正常

![image](https://github.com/Bush2021/chrome_plus/assets/19500576/fde3e7bb-a7e2-4009-bfe3-eae887679968)

> 比如onetab插件、Bitwarden插件、宝塔后台管理、哔哩哔哩直播（无痕模式也不行）

![image](https://github.com/Bush2021/chrome_plus/assets/19500576/ada9201b-62b6-4bc1-9f31-07a6241a6d61)

> `chrome://flags/` 

![image](https://github.com/Bush2021/chrome_plus/assets/19500576/f194e472-94df-468b-a0ad-3f2bdd9feadd)

**Comment by YorkWaugh** [comment]
Please provide your chrome++ configuration. (chrome++.ini)

**Comment by lkeme** [comment]
没有任何修改，每次更新都是全覆盖

**Comment by lkeme** [comment]
可用，测试一切正常

**Comment by Bush2021** [comment]
这个问题其实没有解决，因为我只是简单地 revert 了 #68 引入的修改；

比较奇怪的是，我本地和虚拟机都没有复现这个问题，而且从反馈来看，大部分用户也没问题；所以我怀疑是你本地环境有冲突，例如杀软；

你可以在虚拟机里试试会不会出现同样的问题。

**Comment by lkeme** [comment]
已测试，确实是本地环境问题。

与mactype的冲突。

**Comment by Bush2021** [comment]
> 已测试，确实是本地环境问题。
> 
> 与mactype的冲突。

[version-alpha-8f3ac7f.zip](https://github.com/Bush2021/chrome_plus/files/15328885/version-alpha-8f3ac7f.zip)

再试试这个？

**Comment by lkeme** [comment]
测试正常，可用

**Comment by Bush2021** [comment]
> 跟楼主一样的问题， 有最新版的mactype安装， chrome plus是全部默认配置 覆盖， 这个c7f 没有fix
> 
> 但是[version-alpha-434d109.zip](https://github.com/Bush2021/chrome_plus/files/15308702/version-alpha-434d109.zip) 这个就正常了

这我就不知道了，自行添加 mactype 排除吧。
