### ISSUE TITLE
Now Working in 32 bit Thorium or Supermium

### ISSUE THREAD

**Issue by DaveH1** [Bush2021/chrome_plus#77]
Hi. I've tried to get this working in the 32 bit legacy versions of Thorium and Supermium on Windows XP.
It doesn't work. I am using the 32 bit version of course.
It doesn't seem to be being recognised at all.
It works fine in the 64 bit version of Google Chrome on Windows 10 (multi-boot machine).
Any idea what's wrong?
Would you expect it to work on Windows XP with 32 bit browsers?
Thanks, Dave.

**Comment by Bush2021** [comment]
#64

**Comment by DaveH1** [comment]
OK, thanks.
A shame, but no problem.
Apart from opening bookmarks in a new tab, the things I want, like double click to close tabs and keeping the browser open when the last tab is closed, are already there in flags, at least on Thorium.
