### ISSUE TITLE
BUG 搜索框自动关闭

### ISSUE THREAD

**Issue by hraxga** [Bush2021/chrome_plus#82]
从1.8.5版本后用CTRL+F搜索网页文本时用鼠标点击上下页，点击速度比较快时会自动关闭搜索文本框（点击搜索框比较快时也会自动关闭）。

**Comment by Bush2021** [comment]
https://github.com/Bush2021/chrome_plus/commit/f776715153e110e4cc5b58722cc68a3e6813e03c 前几天修过了，你可以先用下面这个版本。

[version-alpha-f776715.zip](https://github.com/user-attachments/files/15514834/version-alpha-f776715.zip)

**Comment by cangkui** [comment]
1.10.0 版本貌似又有这个问题

**Comment by Bush2021** [comment]
> 1.10.0 版本貌似又有这个问题

有问题请去开一个包含有效信息的 issue，而不是在已经关了的 issue 里指出这个问题 “貌似又有”。
