### ISSUE TITLE
适配ARM版Chrome的可能性？

### ISSUE THREAD

**Issue by bzkmsjy** [Bush2021/chrome_plus#88]
我用不惯edge和safari，而且对谷歌账户同步需求很大，无论是woa还是mac，我都需要一个“符合国人使用习惯”的Chrome，所以想请问下这个项目将来有没有适配ARM平台的打算，难度是否较大？这对我购买新电脑时的平台选择很重要，谢谢

**Comment by Bush2021** [comment]
需要换钩子库，且开发者没有设备和需求，所以我不能保证支持；等有时间了看看。

**Comment by Bush2021** [comment]
https://github.com/Bush2021/chrome_plus/releases/tag/1.9.0-alpha

供测试，请提供反馈。

**Comment by bzkmsjy** [comment]
> https://github.com/Bush2021/chrome_plus/releases/tag/1.9.0-alpha
> 
> 供测试，请提供反馈。

小米book12.4 骁龙8cx gen2测试，无法启动Chrome，管理员权限运行也不行，Cache和Data文件夹也没有生成任何文件。

**Comment by Bush2021** [comment]
[RawCreateFile](https://nightly.link/YorkWaugh/chrome_plus/actions/runs/10498613503/Chrome%2B%2B_arm64.zip)

请测试。我在虚拟机中测试是能够正常启动的。

**Comment by Bush2021** [comment]
请测试最新 release。

**Comment by bzkmsjy** [comment]
> 请测试最新 release。

感谢更新，chrome128测试可用，滚轮切换标签、新标签打开收藏夹、双击关闭标签都可用，其他功能待测。

但是有个奇怪的现象，我必须在资源管理器里右键chrome.exe并选择以管理员权限运行，才能打开它，快捷方式和任务栏图标都无法启动，即便我已经在属性里勾选了以管理员权限运行，我用的是安装版，目录在C:\Program Files\，不知道是不是和这个有关？

**Comment by Bush2021** [comment]
> 感谢更新，chrome128测试可用，滚轮切换标签、新标签打开收藏夹、双击关闭标签都可用，其他功能待测。
> 
> 但是有个奇怪的现象，我必须在资源管理器里右键chrome.exe并选择以管理员权限运行，才能打开它，快捷方式和任务栏图标都无法启动，直接双击本体也无法启动，即便我已经在属性里勾选了以管理员权限运行，我用的是安装版，目录在C:\Program Files\，不知道是不是和这个有关？

是的，在 Program Files 下存在权限问题是预期行为；你应该在其它非特权目录下使用，以避免此问题。
