### ISSUE TITLE
打印失效

### ISSUE THREAD

**Issue by wjw465150** [Bush2021/chrome_plus#89]
发现不能打印网页!
Chrome 版本 126.0.6478.115 32位
![1](https://github.com/Bush2021/chrome_plus/assets/927155/a628d0e7-eedd-479d-9379-8a4ab8c81433)

**Comment by pijiugaizi** [comment]
加启动参数 --disable-features=PrintCompositorLPAC

https://issues.chromium.org/issues/338553158
https://issues.chromium.org/issues/339994760

**Comment by wjw465150** [comment]
谢谢,加上 `--disable-features=PrintCompositorLPAC` 参数就可以打印了!

**Comment by coo11** [comment]
还是有个疑问，如何把这个参数写到 `chrome++.ini` 中？
```ini
; 追加 Chromium 启动参数
; 可以模仿下面的形式来写，注意空格，不要换行
; CommandLine=--no-first-run --disable-logging --no-report-upload
CommandLine=--disable-features=PrintCompositorLPAC
```
这样写似乎不起作用。
