### ISSUE TITLE
谷歌浏览器在开发者模式下安装的非谷歌应用商店插件，浏览器换在虚拟机环境下，之前安装的插件消失

### ISSUE THREAD

**Issue by shanghai20068** [Bush2021/chrome_plus#92]
你好，谷歌浏览器使用最新版chrome_plus，在开发者模式下安装的非谷歌应用商店里面的插件，浏览器换在虚拟机环境下，之前安装的插件消失。请问这是谷歌浏览器的限制，还是插件不完美呢？有办法可以解决吗？

**Comment by Bush2021** [comment]
手动加载的扩展是以绝对路径保存在配置中的，一般来说，被加载的扩展位置不变的话不会丢失；如果更换了位置浏览器会找不到扩展，自然也无法加载。

**Comment by Alvin9999** [comment]
谢谢解惑。确实是绝对路径，请问大佬知道如何修改成相对路径吗？我没有找到位置。

**Comment by xiaopangzi13140** [comment]
请问怎么修改成相对路径呢？

**Comment by xiaopangzi13140** [comment]
没有找到位置
