### ISSUE TITLE
在任意网页视频全屏模式下退出全屏书签栏无法正常呼出菜单

### ISSUE THREAD

**Issue by HanCnz** [Bush2021/chrome_plus#93]
大佬你好，开启新建前台标签页打开书签，在任意网页视频全屏模式下再退出全屏，无法点击书签栏最右边呼出所有书签栏文件夹下面的书签，包括>>符号里面的书签也无法呼出，如下图所示。而书签栏左侧文件夹下面的书签不受影响，在窗口最大化模式下没有任何影响
还望大佬给修复下，谢谢
![Video_2024-07-18_055818000](https://github.com/user-attachments/assets/555d5aac-88da-4d41-8b54-c2fa07dd96b0)

**Comment by Bush2021** [comment]
[version-alpha-1a8fc6f.zip](https://github.com/user-attachments/files/16286828/version-alpha-1a8fc6f.zip)

请尝试是否正常。

**Comment by HanCnz** [comment]
> [version-alpha-c19d8fd.zip](https://github.com/user-attachments/files/16289397/version-alpha-c19d8fd.zip)
> 
> 请尝试是否正常。

非常感谢，目前恢复正常了
