### ISSUE TITLE
依然经常提示：有新版Chrome可用

### ISSUE THREAD

**Issue by yleafcc** [Bush2021/chrome_plus#95]
使用Chrome++，浏览器右上角依然时不时会提示“有新版Chrome可用”，虽然操作重新启动并没有真的更新。能否完全去除提醒呢？
![image](https://github.com/user-attachments/assets/9729d330-ff83-4533-b9b5-8a59e1deb318)

我已经测试过多次，均可重现。

**Comment by yleafcc** [comment]
开始提示"无法更新Chrome"了，能不能处理掉呢？
![image](https://github.com/user-attachments/assets/4a067e40-5dcb-4fb5-b625-311f8c78728b)

**Comment by Bush2021** [comment]
https://github.com/Bush2021/chrome_plus/issues/10#issuecomment-2300036759
