### ISSUE TITLE
关于绿色版chrome打印预览失败的解决方法

### ISSUE THREAD

**Issue by wgetnz** [Bush2021/chrome_plus#96]
从秋风于渭水的博客看到了解决方法，实测成功解决问题
添加权限ALL APPLICATION PACKAGES即可

秋风于渭水的解决方法文章：https://www.tjsky.net/tutorial/996

**Comment by Bush2021** [comment]
#85 临时解决方法早就在 chromium issues 区给出了，你们还要自以为是地从所谓“外网”、“博客”转载过来，真是过于热心了。

**Comment by Bush2021** [comment]
> > #85 临时解决方法早就在 chromium issues 区给出了，你们还要自以为是地从所谓“外网”、“博客”转载过来，真是过于热心了。
> 
> 国内能访问https://issues.chromium.org/ ？分享下解决方法让更多人看到就是 自以为是了？你一个人知道就当所有人知道了？--disable-features=PrintCompositorLPAC真就能修复你真试过了？

是的，我不需要你分享让更多人看到，我一个人知道就够了。
