### ISSUE TITLE
new_tab_disable=1  这一项设置在 Chrome++ 1.9.0 下失效

### ISSUE THREAD

**Issue by shuaiyewl** [Bush2021/chrome_plus#98]
new_tab_disable=1  这一项设置在 Chrome++ 1.9.0 下失效，在 chrome++ 1.8.9下还是有效的。

**Comment by shuaiyewl** [comment]
我的设置：
double_click_close=1
right_click_close=0
keep_last_tab=1
wheel_tab=0
wheel_tab_when_press_rbutton=0
open_url_new_tab=1
open_bookmark_new_tab=1
new_tab_disable=1
new_tab_disable_name="about:blank","新建标签"

**Comment by Bush2021** [comment]
我无法复现。

**Comment by shuaiyewl** [comment]
> 未能复现。

你未能复现是因为你用的书签根目录下的来测试的，要拿书签里子目录里的来测试才行。

**Comment by Bush2021** [comment]
> 你 未 能 复 现 是因为你用的书签根目录下的来测试的，要拿书签里子目录里的来测试才行。

你觉得你刚刚说清楚了吗？

**Comment by shuaiyewl** [comment]
> > 你 未 能 复 现 是因为你用的书签根目录下的来测试的，要拿书签里子目录里的来测试才行。
> 
/
> 你觉得你刚刚说清楚了吗？

就是这样在书签里建立子目录，在这子目录里放置的书签，因为书签多，如果不分类就太散乱了。
![QQ图片20240826200919](https://github.com/user-attachments/assets/127a392c-6b3c-4997-beca-93eb7e94dc31)

**Comment by Bush2021** [comment]
https://github.com/Bush2021/chrome_plus/blob/ac253f0a0af4d12dce972f7b6c9b96bc2db82369/src/iaccessible.h#L402
一般这种情况可以通过配置 new_tab_disable_name 解决；要启用这个功能，需要添加启动参数：`--force-renderer-accessibility=basic`。

**Comment by shuaiyewl** [comment]
我试了添加这个启动参数，也配置了new_tab_disable_name，还是不行，v1.9.0版下新标签页还是不能原地打开书签子目录里的书签。
v1.8.9版无须上述任何配置，直接就是支持的啊。

**Comment by Bush2021** [comment]
> 我试了添加这个启动参数，也配置了new_tab_disable_name，还是不行，v1.9.0版下新标签页还是不能原地打开书签子目录里的书签。 v1.8.9版无须上述任何配置，直接就是支持的啊。

显然我在标准环境下测试了可行性，你不行是你自己操作或者环境的问题；我关了这个 issue，说明会在下个版本解决，你也可以直接用下面的版本。

[version-alpha-9492f00.zip](https://github.com/user-attachments/files/16761340/version-alpha-9492f00.zip)
