### ISSUE TITLE
下载列表无法直接打开文件

### ISSUE THREAD

**Issue by ace115** [Bush2021/chrome_plus#99]
1.90版本出现此问题
![屏幕截图 2024-08-30 144958](https://github.com/user-attachments/assets/368f8f8c-f25e-40f4-aee2-70c7d6527ea2)
![屏幕截图 2024-08-30 145024](https://github.com/user-attachments/assets/4cb3a08b-e478-4092-a649-5d6178690322)
![屏幕截图 2024-08-30 145439](https://github.com/user-attachments/assets/15ed880f-f2fb-4ad1-9652-f96f24f4d67f)

**Comment by Bush2021** [comment]
[version-alpha-3cf8f81.zip](https://github.com/user-attachments/files/16872899/version-alpha-3cf8f81.zip)
